spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: LXMXLMX666


logging:
  level:
    root: info
    com.ustc: debug
mybatis:
  mapper-locations: classpath:com/ustc/mapper/*.xml
  type-aliases-package: com.ustc.pojo

pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
